const KEY="ayush9845_neet_tracker_v1";
const subjects={Physics:["Units & Measurements","Motion in a Straight Line","Motion in a Plane","Laws of Motion","Work, Energy & Power","System of Particles & Rotation","Gravitation","Mechanical Properties","Thermodynamics","Kinetic Theory","Oscillations","Waves","Electrostatics","Current Electricity","Moving Charges & Magnetism","EMI & AC","Electromagnetic Waves","Ray Optics","Wave Optics","Dual Nature","Atoms","Nuclei","Semiconductors"],Chemistry:["Some Basic Concepts","Structure of Atom","Classification & Periodicity","Chemical Bonding","Thermodynamics","Equilibrium","Redox Reactions","Organic Chemistry Basics","Hydrocarbons","Solutions","Electrochemistry","Chemical Kinetics","Surface Chemistry","p-Block Elements","d & f Block Elements","Coordination Compounds","Haloalkanes & Haloarenes","Alcohols, Phenols & Ethers","Aldehydes, Ketones & Acids","Amines","Biomolecules"],Biology:["The Living World","Biological Classification","Plant Kingdom","Animal Kingdom","Morphology of Flowering Plants","Anatomy of Flowering Plants","Structural Organisation in Animals","Cell: The Unit of Life","Biomolecules","Cell Cycle & Division","Transport in Plants","Mineral Nutrition","Photosynthesis","Respiration in Plants","Plant Growth & Development","Digestion & Absorption","Breathing & Exchange of Gases","Body Fluids & Circulation","Excretory Products","Locomotion & Movement","Neural Control","Chemical Coordination","Reproduction in Organisms","Sexual Reproduction in Flowering Plants","Human Reproduction","Reproductive Health","Principles of Inheritance","Molecular Basis of Inheritance","Evolution","Human Health & Disease","Strategies for Enhancement","Microbes in Human Welfare","Biotechnology Principles","Biotechnology Applications","Organisms & Populations","Ecosystem","Biodiversity & Conservation"]};
const blank=()=>({username:"@Ayush9845",college:"AIIMS New Delhi",target:710,best:0,study:{},tasks:[],tests:[],done:{Physics:{},Chemistry:{},Biology:{}}});
let data=JSON.parse(localStorage.getItem(KEY)||"null")||blank(); const today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function toast(s){const t=document.querySelector("#toast");t.textContent=s;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),1800)}
function go(tab){document.querySelectorAll(".tab-panel").forEach(x=>x.classList.toggle("hidden",x.id!==tab));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>go(b.dataset.tab));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
function countdown(){const end=new Date("2027-06-04T14:00:00+05:30"),d=Math.max(0,end-Date.now()),s=Math.floor(d/1000),days=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;document.querySelector("#countdown").textContent=`${days}d  ${String(h).padStart(2,"0")}h  ${String(m).padStart(2,"0")}m  ${String(sec).padStart(2,"0")}s`}setInterval(countdown,1000);countdown();
function subProgress(s){const arr=subjects[s],done=Object.values(data.done[s]||{}).filter(Boolean).length;return Math.round(done/arr.length*100)}
function renderChapters(sub="Physics"){document.querySelectorAll(".mini-tab").forEach(b=>b.classList.toggle("active",b.dataset.sub===sub));document.querySelector("#chapters").innerHTML=subjects[sub].map((c,i)=>`<div class="chapter"><input type="checkbox" ${data.done[sub][i]?"checked":""} data-ch="${i}"><label>${c}</label><span class="tag">${data.done[sub][i]?"Completed":"Not started"}</span></div>`).join("");document.querySelectorAll("[data-ch]").forEach(x=>x.onchange=()=>{data.done[sub][x.dataset.ch]=x.checked;save()});}
document.querySelectorAll(".mini-tab").forEach(b=>b.onclick=()=>renderChapters(b.dataset.sub));
function renderTasks(){const el=document.querySelector("#tasks"),ts=data.tasks.filter(x=>x.date===today());document.querySelector("#taskCount").textContent=`${ts.length} task${ts.length!==1?"s":""}`;document.querySelector("#todayTasks").textContent=ts.filter(x=>x.done).length;el.innerHTML=ts.length?ts.map(x=>`<div class="task ${x.done?"done":""}"><input class="check" type="checkbox" ${x.done?"checked":""} data-task="${x.id}"><span class="task-title">${x.text}</span><span class="tag">${x.subject} · ${x.mins}m</span><button class="delete" data-del="${x.id}">×</button></div>`).join(""):`<div class="empty">No tasks yet. Add one small, specific task above.</div>`;document.querySelectorAll("[data-task]").forEach(x=>x.onchange=()=>{let t=data.tasks.find(t=>t.id==x.dataset.task);t.done=x.checked;save()});document.querySelectorAll("[data-del]").forEach(x=>x.onclick=()=>{data.tasks=data.tasks.filter(t=>t.id!=x.dataset.del);save()})}
document.querySelector("#addTask").onclick=()=>{let text=document.querySelector("#taskText").value.trim();if(!text)return toast("Enter a task first");data.tasks.push({id:Date.now(),date:today(),subject:document.querySelector("#taskSubject").value,text,mins:+document.querySelector("#taskMins").value||60,done:false});document.querySelector("#taskText").value="";save();toast("Task added")};
document.querySelector("#addStudy").onclick=()=>{const m=+document.querySelector("#focusMinutes").value||0;if(!m)return;data.study[today()]=(data.study[today()]||0)+m;save();toast(`${m} minutes logged`)};
document.querySelector("#saveScore").onclick=()=>{data.best=Math.max(0,Math.min(720,+document.querySelector("#bestScore").value||0));save();toast("Best score saved")};
document.querySelector("#addTest").onclick=()=>{const name=document.querySelector("#testName").value.trim()||"Mock Test",score=Math.max(0,Math.min(720,+document.querySelector("#testScore").value||0));data.tests.push({name,score,date:document.querySelector("#testDate").value||today()});save();toast("Test logged");["#testName","#testScore"].forEach(s=>document.querySelector(s).value="")};
function renderTests(){const el=document.querySelector("#testsList");el.innerHTML=data.tests.slice().reverse().map(t=>`<div class="task"><span class="tag">${t.date}</span><span class="task-title">${t.name}</span><b>${t.score}/720</b></div>`).join("")||`<div class="empty">No mock tests logged yet.</div>`}
function renderAnalytics(){let bars=document.querySelector("#bars");bars.innerHTML=Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-(6-i));let k=d.toISOString().slice(0,10),v=data.study[k]||0;return `<div class="bar-col"><div class="bar"><i style="height:${Math.min(100,v/360*100)}%"></i></div><small>${k.slice(5)}</small></div>`}).join("");document.querySelector("#scoreTrend").innerHTML=data.tests.slice(-8).map(t=>`<div class="score-item"><span>${t.name}</span><b>${t.score}</b></div>`).join("")||"<div class='empty'>Log mocks to see your trend.</div>"}
function render(){document.querySelector(".brand-name").textContent=data.username;document.querySelector("footer b").textContent=data.username;document.querySelector("#collegeName").textContent=data.college;document.querySelector("#targetScore").textContent=data.target;document.querySelector("#bestScore").value=data.best;const mins=data.study[today()]||0;document.querySelector("#todayFocus").textContent=mins;document.querySelector("#todayHours").textContent=(mins/60).toFixed(1);document.querySelector("#todayProgress").style.width=Math.min(100,mins/360*100)+"%";document.querySelector("#scoreProgress").style.width=(data.best/data.target*100)+"%";["Physics","Chemistry","Biology"].forEach(s=>{let p=subProgress(s);let id=s[0].toLowerCase();document.querySelector(`#${id}Prog`).textContent=p+"%";document.querySelector(`#${id}Bar`).style.width=p+"%"});let all=Object.keys(subjects).reduce((a,s)=>a+subProgress(s),0)/3;document.querySelector("#overallProg").textContent=Math.round(all)+"%";renderTasks();renderTests();renderAnalytics()}
document.querySelector("#settingsBtn").onclick=()=>document.querySelector("#settings").classList.remove("hidden");document.querySelector("#closeSettings").onclick=()=>document.querySelector("#settings").classList.add("hidden");
document.querySelector("#saveSettings").onclick=()=>{data.username=document.querySelector("#usernameInput").value.trim()||"@Ayush9845";data.college=document.querySelector("#collegeInput").value.trim()||"AIIMS New Delhi";data.target=+document.querySelector("#targetInput").value||710;save();document.querySelector("#settings").classList.add("hidden");toast("Settings saved")};
document.querySelector("#resetData").onclick=()=>{if(confirm("Reset all tracker data?")){data=blank();save();toast("Data reset")}};
document.querySelector("#pomodoro").onclick=()=>{let sec=25*60;const w=window.open("","_blank","width=360,height=280");if(!w)return;w.document.write(`<body style="background:#090b12;color:#7cf7c0;font:800 32px system-ui;text-align:center;padding-top:55px"><div>FOCUS SPRINT</div><div id=x style="font-size:54px;margin-top:15px">25:00</div><script>let s=1500;setInterval(()=>{s--;document.querySelector('#x').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},1000)<\/script></body>`)};
document.querySelector("#testDate").value=today();renderChapters();render();
